### PR TITLE
docs: add READMEs to /.github, /build and /cmd directories

### PR DESCRIPTION
**Pull request by geoffturk**
Part of #459 

Regarding the `/cmd/README.md`, it is more detailed than for what we will write for the rest of the codebase, but the aim is to make it easy for Go newbies to understand how Go programs are launched.

Ditto for those unfamiliar with GitHub Actions/Workflows and Docker.

### CODE REVIEW

**Comment by maxsarratt** [comment]
I'm fine with adding comments to the README, but do we expect people who want to contribute to this project to be Go beginners?

**Comment by geoffturk** [comment]
> I'm fine with adding comments to the README, but do we expect people who want to contribute to this project to be Go beginners?

Not necessarily. The purpose of adding the comments is to enable anyone interested to get an understanding about how the entire project fits together.

**Review by maxsarratt — APPROVED** [review]
LGTM 👍

**Comment by maxsarratt** [comment]
I see. Let's see how it goes.

**Pull request merged**
