### PR TITLE
fix: should set post_failed when es is dead

### PR DESCRIPTION
**Pull request by maxlivinci**

### CODE REVIEW

**Comment by geoffturk** [comment]
image

OK, it's working now.

When Elasticsearch eventually comes back online, profiles with `post_failed` status should automatically be retried. Is this already enabled or should we create a new issue for it?

**Comment by geoffturk** [comment]
Also, please add a message to the `failure_reasons`: "Profile not posted to index. Will reattempt soon when service is fully operational."

**Comment by maxlivinci** [comment]
> Also, please add a message to the `failure_reasons`: "Profile not posted to index. Will reattempt soon when service is fully operational."

https://github.com/MurmurationsNetwork/MurmurationsServices/issues/32

**Review by geoffturk — APPROVED** [review]
LGTM 🚀

**Pull request merged**
