### PR TITLE
Document Manual Intervention for Node Failures

### LINKED ISSUE #759: Document Manual Intervention for Node Failures

### PR DESCRIPTION
**Pull request by vthwang**
Resolved #759

### CODE REVIEW

**Review by maxyzli — COMMENTED** [review]
Do we need to update the READEME in the rancher folder?

**Comment by vthwang** [comment]
> Do we need to update the READEME in the rancher folder?

Moved to "debugging guide" folder.

**Review by maxyzli — APPROVED** [review]
LGTM

**Review by geoffturk — APPROVED** [review]
LGTM

**Pull request merged**
