### PR TITLE
feat: Return all batch import errors at once

### LINKED ISSUE #823: Improve error response from batch endpoint
Replaces #736 

- [x] Only list schema name and don't include the entire schema (resolved in #821)
- [x] Return all of the errors at once, not one at a time
- [x] Show row number and `oid` of profile that caused the error (for each error, not in meta at the end of the JSON doc)

### PR DESCRIPTION
**Pull request by maxyzli**
resolves #823

### CODE REVIEW

**Comment by maxyzli** [comment]
@geoffturk 

image

- Return all errors at once, not one at a time.
- Show the OID of the profile that caused each error.

Regarding showing the row number, it's extremely difficult because the raw information is lost once we convert to a Go map and perform the validation.

**Review by geoffturk — APPROVED** [review]
LGTM 🚀

**Review by geoffturk — CHANGES_REQUESTED** [review]
This works well. Please add another CSV file to the test directory with two nodes that both produce errors and write an e2e test to ensure the errors are displayed along with their `oid`s.

**Review by geoffturk — APPROVED** [review]
LGTM

**Pull request merged**
