### PR TITLE
refactor: Enable auto-deletion of nodes with expires field

### LINKED ISSUE #829: Enable auto-deletion of nodes with `expires` field
# Auto-Delete Expired Profiles

There is a use case for certain profiles to “expire” at a specific date/time and marked as deleted in the index. For example, a time-sensitive offer/want that is irrelevant after a specific period can be automatically removed from the index and thus no longer be searchable.

- Enable profiles to “expire” after a specific date/time
   - Add `expires` field to default schema
      - Number type, not required
   - Index the value for this field if set in a profile
   - Add `expires` to list of searchable parameters at the `GET /nodes` endpoint
   - Change profile status from `posted` to `deleted` when the expiry date/time is reached
      - `nodecleaner` service will do this every time it runs

- Logic
   - If a profile is validated/posted with an `expires` value that is past the current date/time, it should be rejected by the index
      - Apply this logic to a new profile or a profile being updated, and even at the `POST /validate` endpoint
      - Also apply it to any profile that did not have an `expires` value when it was first posted, but that has it added in a subsequent post to the index
   - If a profile that was marked `deleted` by the index when it expired is reposted with a new `expires` value that is in the future, update the profile in the index and change its status back to `posted`

### PR DESCRIPTION
**Pull request by maxyzli**
resolves #829

### CODE REVIEW

**Comment by maxyzli** [comment]
We have to add `default-v3.0.0` in order to create the expires field.

https://github.com/MurmurationsNetwork/MurmurationsLibrary/pull/132

**Comment by maxyzli** [comment]
When querying the API `/nodes`, we can use `expires` as a keyword for searching.

For example, if I pass in `expires=1728938932`, the system will return all results where the expires field is `LESS THAN` or `EQUAL TO` that timestamp.

**Comment by geoffturk** [comment]
Adding the `expires` field is not a breaking change to existing profile instances so I changed it to v2.1. When we finally add breaking changes to the default schema, we'll probably be changing the API version (v2->v3) at the same time.

**Review by geoffturk — APPROVED** [review]
LGTM

**Pull request merged**
